package com.model;
// Generated 6/05/2017 04:28:50 PM by Hibernate Tools 5.2.1.Final

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer idLibro;
	private Autor autor;
	private Categoria categoria;
	private Editorial editorial;
	private Idioma idioma;
	private String titulo;

	public Libro() {
	}

	public Libro(Autor autor, Categoria categoria, Editorial editorial, Idioma idioma, String titulo) {
		this.autor = autor;
		this.categoria = categoria;
		this.editorial = editorial;
		this.idioma = idioma;
		this.titulo = titulo;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Editorial getEditorial() {
		return this.editorial;
	}

	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}

	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

}
